# Generated by Django 3.2 on 2023-03-16 15:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_auto_20230309_1550'),
        ('profiles', '0003_remove_userprofile_default_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('rating',
                 models.IntegerField(
                     validators=[
                         django.core.validators.MinValueValidator(0),
                         django.core.validators.MaxValueValidator(5)])),
                ('review_title',
                 models.CharField(
                     blank=True,
                     max_length=100,
                     null=True)),
                ('review',
                 models.TextField(
                     blank=True,
                     null=True)),
                ('product',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='p_ratings',
                     to='products.product')),
                ('user_profile',
                 models.ForeignKey(
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     to='profiles.userprofile')),
            ],
        ),
    ]
